-keep class com.example.lovecounter.data.model.** { *; }
-keep,allowobfuscation,allowshrinking class retrofit2.Response
-keep,allowobfuscation,allowshrinking class kotlin.coroutines.Continuation
-dontwarn org.slf4j.impl.StaticLoggerBinder
-keep public class com.android.installreferrer.** { *; }